CLASS zvzx_000 DEFINITION INHERITING FROM cx_no_check
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS lm_exc IMPORTING i_input TYPE string.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zvzx_000 IMPLEMENTATION.

  METHOD lm_exc.
    MESSAGE ID '00' TYPE 'E' NUMBER '001' WITH i_input.
    EXIT.
  ENDMETHOD.

ENDCLASS.